import Head from "next/head";
import Image from "next/image";
import Footer from "./component/Footer";
import Header from "./component/Header";
import Main from "./component/Main";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="wrap">
        {/* header */}
        <Header />
        {/* main */}
        <Main />
        {/* footer */}
        <Footer />
      </div>
      <style jsx>{`
        .wrap {
          width: 100%;
          height: 100vh;
        }
      `}</style>
    </>
  );
}
